# -*- coding: utf-8 -*-
"""TinyGPT Modified

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X7GDi28U1EVHKc8R3A7PNBpqGX3kmFXT
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from pathlib import Path
import urllib.request
import time

try:
    from tqdm import tqdm
except ImportError:
    class tqdm:
        def __init__(self, iterable, **kwargs):
            self.iterable = iterable
        def __iter__(self):
            return iter(self.iterable)
        def set_postfix(self, **kwargs):
            pass

# =====================================================================
# [1] 데이터 파이프라인: 커스텀 텍스트 데이터 로드
# =====================================================================

DATA_FILE = "custom_data.txt"

if not Path(DATA_FILE).exists():
    print(f"⚠️ '{DATA_FILE}' 파일이 없어 기본 예제(이상한 나라의 앨리스)를 다운로드합니다.")
    url = "https://www.gutenberg.org/cache/epub/11/pg11.txt"
    urllib.request.urlretrieve(url, DATA_FILE)

text = open(DATA_FILE, "r", encoding="utf-8").read()
chars = sorted(list(set(text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}
vocab_size = len(chars)

print(f"데이터 로드 완료: 총 글자 수 {len(text):,}자, 고유 문자 {vocab_size}개")

data = torch.tensor([stoi[ch] for ch in text], dtype=torch.long)

class NextTokenDataset(Dataset):
    def __init__(self, data, block_size):
        self.data = data
        self.block_size = block_size

    def __len__(self):
        return len(self.data) - self.block_size

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.block_size]
        y = self.data[idx + 1 : idx + self.block_size + 1]
        return x, y

block_size = 64
dataset = NextTokenDataset(data, block_size)
loader = DataLoader(dataset, batch_size=64, shuffle=True)


# =====================================================================
# [2] 어텐션 레이어 및 모델 아키텍처
# =====================================================================

class Head(nn.Module):
    def __init__(self, emb_dim, head_size, block_size, dropout=0.1):
        super().__init__()
        self.key = nn.Linear(emb_dim, head_size, bias=False)
        self.query = nn.Linear(emb_dim, head_size, bias=False)
        self.value = nn.Linear(emb_dim, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        v = self.value(x)
        wei = q @ k.transpose(-2, -1) * (k.size(-1) ** -0.5)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf"))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        head_size = emb_dim // num_heads
        self.heads = nn.ModuleList([Head(emb_dim, head_size, block_size, dropout) for _ in range(num_heads)])
        self.proj = nn.Linear(emb_dim, emb_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.proj(out)
        out = self.dropout(out)
        return out

class FeedForward(nn.Module):
    def __init__(self, emb_dim, dropout=0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(emb_dim, 4 * emb_dim),
            nn.ReLU(),
            nn.Linear(4 * emb_dim, emb_dim),
            nn.Dropout(dropout),
        )
    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        self.ln1 = nn.LayerNorm(emb_dim)
        self.sa = MultiHeadAttention(emb_dim, num_heads, block_size, dropout)
        self.ln2 = nn.LayerNorm(emb_dim)
        self.ffwd = FeedForward(emb_dim, dropout)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class TinyGPT(nn.Module):
    def __init__(self, vocab_size, block_size, emb_dim=128, num_heads=4, num_layers=4, dropout=0.1):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, emb_dim)
        self.position_embedding = nn.Embedding(block_size, emb_dim)
        self.blocks = nn.Sequential(*[
            Block(emb_dim, num_heads, block_size, dropout) for _ in range(num_layers)
        ])
        self.ln_f = nn.LayerNorm(emb_dim)
        self.lm_head = nn.Linear(emb_dim, vocab_size)

    def forward(self, x):
        B, T = x.shape
        pos = torch.arange(T, device=x.device)
        tok = self.token_embedding(x)
        pos = self.position_embedding(pos)[None]
        h = tok + pos
        h = self.blocks(h)
        h = self.ln_f(h)
        logits = self.lm_head(h)
        return logits

# =====================================================================
# [3] 학습 루틴: 1500 에포크 하드 트레이닝 및 진행률 출력 최적화
# =====================================================================

def sequence_cross_entropy(logits, targets):
    return F.cross_entropy(logits.transpose(1, 2), targets)

def train_one_epoch(model, loader, optimizer, device, max_steps=None):
    model.train()
    total_loss, total_count = 0.0, 0

    # 💡 [수정] 매 에포크마다 진행바가 생기면 로그가 지저분해지므로 tqdm 비활성화 (내부 진행만 계산)
    for step, (xb, yb) in enumerate(loader):
        xb, yb = xb.to(device), yb.to(device)

        logits = model(xb)
        loss = sequence_cross_entropy(logits, yb)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * xb.size(0)
        total_count += xb.size(0)

        if max_steps is not None and step + 1 >= max_steps:
            break
    return total_loss / total_count

device = "cuda" if torch.cuda.is_available() else "cpu"
model = TinyGPT(vocab_size, block_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

TOTAL_EPOCHS = 1500
LOG_INTERVAL = 50  # 💡 50 에포크 단위로 묶어서 출력

print(f"\n🚀 총 {TOTAL_EPOCHS} 에포크 학습을 시작합니다... (디바이스: {device})")
print(f"📊 진행 상황은 {LOG_INTERVAL} 에포크마다 업데이트됩니다.\n")

start_time = time.time()
running_loss = 0.0

# 💡 [수정] 진행도를 보기 좋게 표시하는 메인 루프
for epoch in range(1, TOTAL_EPOCHS + 1):
    train_loss = train_one_epoch(model, loader, optimizer, device, max_steps=300)
    running_loss += train_loss

    # 50 에포크마다 묶어서 결과 출력
    if epoch % LOG_INTERVAL == 0:
        avg_loss = running_loss / LOG_INTERVAL
        progress_pct = (epoch / TOTAL_EPOCHS) * 100
        elapsed_time = time.time() - start_time

        # 진행률 바(Progress Bar) 만들기
        bar_length = 20
        filled_length = int(bar_length * epoch // TOTAL_EPOCHS)
        bar = '█' * filled_length + '-' * (bar_length - filled_length)

        print(f"[{epoch:4d}/{TOTAL_EPOCHS}] |{bar}| {progress_pct:5.1f}% | 평균 Loss: {avg_loss:.4f} | 경과 시간: {elapsed_time:.1f}초")

        # 다음 구간을 위해 누적 loss 초기화
        running_loss = 0.0

print(f"\n✨ 학습 완료! 총 소요 시간: {time.time() - start_time:.1f}초")


# =====================================================================
# [4] 생성 및 파일 저장 (이메일 제출용)
# =====================================================================

@torch.no_grad()
def sample_gpt(model, block_size, stoi, itos, device, start_text="The ", max_new_tokens=1000):
    model.eval()
    context = torch.zeros((1, block_size), dtype=torch.long, device=device)
    for ch in start_text:
        if ch in stoi:
            ix = torch.tensor([[stoi[ch]]], device=device)
            context = torch.cat([context[:, 1:], ix], dim=1)

    out = list(start_text)
    for _ in range(max_new_tokens):
        logits = model(context)
        logits = logits[:, -1, :]
        probs = F.softmax(logits, dim=-1)
        ix = torch.multinomial(probs, num_samples=1)
        out.append(itos[ix.item()])
        context = torch.cat([context[:, 1:], ix], dim=1)
    return "".join(out)

print("\n[추론 시작] 텍스트를 생성 중입니다...")
generated_text = sample_gpt(model, block_size, stoi, itos, device, start_text="The ", max_new_tokens=1000)

output_filename = "result_for_professor.txt"
with open(output_filename, "w", encoding="utf-8") as f:
    f.write(f"--- TinyGPT {TOTAL_EPOCHS} Epoch 학습 결과 ---\n\n")
    f.write(generated_text)

print(f"✅ 결과물이 '{output_filename}' 파일로 저장되었습니다.")